name: Hello World, JLSeto
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false

# Google Analytics
#google_analytics: UA-108597035-1
